# Use a minimal Node.js runtime image
FROM node:18-alpine
# Set the working directory
WORKDIR /app
# Copy package.json and package-lock.json
COPY package.json package-lock.json ./
# Install production dependencies
# RUN npm install
RUN npm ci --only=production
# Copy application source code
ARG ALLOWED_FILE_TYPES
ARG ALLOWED_ORIGINS
ARG AWS_ACCOUNT_NAME
ARG AWS_CLIENT_ID
ARG AWS_CONTAINER_NAME
ARG CHATAI_STATUS_COMPLETED
ARG CHATAI_STATUS_INPROGRESS
ARG DB_DIALECT
ARG DB_HOST
ARG DB_NAME
ARG DB_PASSWORD
ARG DB_USER
ARG DEFAULT_LIMIT
ARG DEFAULT_PAGE
ARG FILE_SIZE_LIMIT
ARG KEYCLOAK_CLIENT_ID
ARG KEYCLOAK_CLIENT_SECRET
ARG KEYCLOAK_REALM
ARG KEYCLOAK_URL
ARG NODE_ENV
ARG PORT
ARG CONVERSATION_AWS_FOLDER_PATH
ARG DOMAIN_URL
ARG LOG_LEVEL
ARG MEDIA_API_ENDPOINT
ARG NODE_TLS_REJECT_UNAUTHORIZED
ARG USE_MANAGED_IDENTITY
ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_PASSWORD
ARG REDIS_SSL
ARG REDIS_EXPIRE
ARG POWERBI_CLIENT_ID
ARG POWERBI_CLIENT_SECRET
ARG POWERBI_TENANT_ID
ARG POWERBI_DEFAULT_WORKSPACE_ID
ARG AZURE_STORAGE_CONNECTION_STRING
ARG ALLOW_CREDENTIALS
ARG AZURE_SEARCH_ENDPOINT
ARG AZURE_SEARCH_KEY
ARG AZURE_SEARCH_INDEX
ARG POWERBI_TOKEN_EXPIRY_MS
ARG POWERBI_API_TIMEOUT_MS
ARG POWERBI_DEMO_REPORT_REC_ID
ARG POWERBI_DEMO_REPORT_RETAIL_ID
ARG MICROSTRATEGY_BASE_URL
ARG MICROSTRATEGY_PROJECT_ID
ARG MICROSTRATEGY_DEFAULT_DASHBOARD_ID
ARG INSIGHTS_DATA_INDEX
ARG LLM_ENDPOINT
ENV LLM_ENDPOINT=$LLM_ENDPOINT
ENV INSIGHTS_DATA_INDEX=$INSIGHTS_DATA_INDEX
ENV MICROSTRATEGY_DEFAULT_DASHBOARD_ID=$MICROSTRATEGY_DEFAULT_DASHBOARD_ID
ENV MICROSTRATEGY_PROJECT_ID=$MICROSTRATEGY_PROJECT_ID
ENV MICROSTRATEGY_BASE_URL=$MICROSTRATEGY_BASE_URL
ENV POWERBI_DEMO_REPORT_RETAIL_ID=$POWERBI_DEMO_REPORT_RETAIL_ID
ENV POWERBI_DEMO_REPORT_REC_ID=POWERBI_DEMO_REPORT_REC_ID
ENV POWERBI_API_TIMEOUT_MS=$POWERBI_API_TIMEOUT_MS
ENV POWERBI_TOKEN_EXPIRY_MS=$POWERBI_TOKEN_EXPIRY_MS
ENV AZURE_SEARCH_INDEX=$AZURE_SEARCH_INDEX
ENV AZURE_SEARCH_KEY=$AZURE_SEARCH_KEY
ENV AZURE_SEARCH_ENDPOINT=$AZURE_SEARCH_ENDPOINT
ENV ALLOW_CREDENTIALS=$ALLOW_CREDENTIALS
ENV AZURE_STORAGE_CONNECTION_STRING=$AZURE_STORAGE_CONNECTION_STRING
ENV POWERBI_DEFAULT_WORKSPACE_ID=$POWERBI_DEFAULT_WORKSPACE_ID
ENV POWERBI_TENANT_ID=$POWERBI_TENANT_ID
ENV POWERBI_CLIENT_SECRET=$POWERBI_CLIENT_SECRET
ENV POWERBI_CLIENT_ID=$POWERBI_CLIENT_ID
ENV REDIS_EXPIRE=$REDIS_EXPIRE
ENV REDIS_SSL=$REDIS_SSL
ENV REDIS_PASSWORD=$REDIS_PASSWORD
ENV REDIS_PORT=$REDIS_PORT
ENV REDIS_HOST=$REDIS_HOST
ENV USE_MANAGED_IDENTITY=$USE_MANAGED_IDENTITY
ENV NODE_TLS_REJECT_UNAUTHORIZED=$NODE_TLS_REJECT_UNAUTHORIZED
ENV AZURE_CLIENT_ID=$AZURE_CLIENT_ID
ENV CHATAI_STATUS_COMPLETED=$CHATAI_STATUS_COMPLETED
ENV CHATAI_STATUS_INPROGRESS=$CHATAI_STATUS_INPROGRESS
ENV MEDIA_API_ENDPOINT=$MEDIA_API_ENDPOINT
ENV LOG_LEVEL=$LOG_LEVEL
ENV DOMAIN_URL=$DOMAIN_URL
ENV CONVERSATION_AZURE_FOLDER_PATH=$CONVERSATION_AZURE_FOLDER_PATH
ENV PORT=$PORT
ENV DB_USER=$DB_USER
ENV NODE_ENV=$NODE_ENV
ENV KEYCLOAK_URL=$KEYCLOAK_URL
ENV KEYCLOAK_REALM=$KEYCLOAK_REALM
ENV KEYCLOAK_CLIENT_SECRET=$KEYCLOAK_CLIENT_SECRET
ENV KEYCLOAK_CLIENT_ID=$KEYCLOAK_CLIENT_ID
ENV FILE_SIZE_LIMIT=$FILE_SIZE_LIMIT
ENV DEFAULT_PAGE=$DEFAULT_PAGE
ENV DEFAULT_LIMIT=$DEFAULT_LIMIT
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_NAME=$DB_NAME
ENV DB_HOST=$DB_HOST
ENV DB_DIALECT=$DB_DIALECT
ENV AZURE_CONTAINER_NAME=$AZURE_CONTAINER_NAME
ENV AZURE_ACCOUNT_NAME=$AZURE_ACCOUNT_NAME
ENV ALLOWED_ORIGINS=$ALLOWED_ORIGINS
ENV ALLOWED_FILE_TYPES=$ALLOWED_FILE_TYPES
COPY . .
# Set environment variables
# ENV NODE_ENV=production
# ENV PORT=5000
# Expose the application port
EXPOSE 5000
# Set environment variables (LOG_LEVEL can be overridden at runtime)
# ENV LOG_LEVEL=info
# Start the application
CMD ["node", "src/app.js"]
