name: Build

on:
  push:
    branches:
      - "**"


jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for a proper analysis

      - name: Set Project Name from Repo
        run: echo "REPO_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV

      # - name: Run Tests & Generate Coverage Report
      #   run: |
      #     pip install pytest pytest-cov  # Ensure dependencies
      #     pytest --cov=src --cov-report=xml  # Run tests & generate XML coverage

      - name: Run SonarQube Analysis
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://sonarqube.deepthought.tigeranalyticstest.in"
        with:
          args: >
            -Dsonar.projectKey=${{ env.REPO_NAME }}
            -Dsonar.projectName=${{ env.REPO_NAME }}
            -Dsonar.sources=.
            -Dsonar.python.coverage.reportPaths=coverage.xml
      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      # - uses: SonarSource/sonarqube-quality-gate-action@v1
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
